/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.*;
import java.time.Clock;
import javax.swing.*;

/**
 *
 * @author luuxu
 */
public class Form_zMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_zMain.class.getName());
    
    /**
     * Creates new form Form_Trangchu
     */
    public Form_zMain() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setExtendedState(MAXIMIZED_BOTH);
        
        jpn_header.setBackground(new Color(41, 128, 185));
        lbl_tieude.setForeground(Color.WHITE);
        jpn_west.setPreferredSize(new Dimension(265, 520));
        jpn_center.setBackground(Color.WHITE);

        //css lai cac menu con
        modifyMenu();
        //add cac panel con
        add_Panel();
    }
    
    private void modifyMenu(){
        jpn_west.setBackground(new Color(52, 73, 94));   // menu nền
        jpn_west.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 10));

        customizeButton(btn_trangchu);
        customizeButton(btn_datphong);
        customizeButton(btn_quanlyphong);
        customizeButton(btn_quanlydatphong);
        customizeButton(btn_quanlykhachhang);
        customizeButton(btn_quanlydichvu);
        customizeButton(btn_taikhoan);
        customizeButton(btn_dangxuat);
        customizeButton(btn_thoat);
    }
    private void customizeButton(javax.swing.JButton btn){
        btn.setFont(new Font("Arial",Font.PLAIN, 14));
        btn.setForeground(Color.WHITE);
        btn.setBackground(new Color(52, 73, 94));

        btn.setFocusPainted(false);
        btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));

        //btn.setPreferredSize(new Dimension(230, 45));
        //btn.setMaximumSize(new Dimension(230, 45));
        ///btn.setMinimumSize(new Dimension(230, 45));
        
         // Hiệu ứng hover
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(41, 128, 185));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(52, 73, 94));
            }
        });
    }
    
    //add cac panel vao frame
    private void add_Panel(){
        jpn_center.add(new Form_Trangchu(), "TRANGCHU");
        jpn_center.add(new Form_Datphong(), "DATPHONG");
        jpn_center.add(new Form_Quanlyphong(), "QUANLYPHONG");
        jpn_center.add(new Form_Quanlydatphong(), "QUANLYDATPHONG");
        jpn_center.add(new Form_Quanlykhachhang(), "QUANLYKHACHHANG");
        jpn_center.add(new Form_Quanlydichvu(), "QUANLYDICHVU");
        jpn_center.add(new Form_Taikhoan(), "TAIKHOAN");

    }
    //hienthi cac panle
    private void show_Panel(String name) {
        CardLayout cl = (CardLayout) jpn_center.getLayout();
        cl.show(jpn_center, name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_header = new javax.swing.JPanel();
        lbl_tieude = new javax.swing.JLabel();
        jpn_west = new javax.swing.JPanel();
        btn_trangchu = new javax.swing.JButton();
        btn_datphong = new javax.swing.JButton();
        btn_quanlyphong = new javax.swing.JButton();
        btn_quanlydatphong = new javax.swing.JButton();
        btn_quanlykhachhang = new javax.swing.JButton();
        btn_quanlydichvu = new javax.swing.JButton();
        btn_taikhoan = new javax.swing.JButton();
        btn_dangxuat = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        jpn_center = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpn_header.setPreferredSize(new java.awt.Dimension(860, 80));

        lbl_tieude.setBackground(new java.awt.Color(0, 153, 204));
        lbl_tieude.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lbl_tieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tieude.setText("HỆ THỐNG QUẢN LÝ KHÁCH SẠN MOONLOGHT");

        javax.swing.GroupLayout jpn_headerLayout = new javax.swing.GroupLayout(jpn_header);
        jpn_header.setLayout(jpn_headerLayout);
        jpn_headerLayout.setHorizontalGroup(
            jpn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_tieude, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        jpn_headerLayout.setVerticalGroup(
            jpn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_tieude, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jpn_header, java.awt.BorderLayout.PAGE_START);

        jpn_west.setPreferredSize(new java.awt.Dimension(250, 520));

        btn_trangchu.setText("TRANG CHỦ");
        btn_trangchu.setMaximumSize(new java.awt.Dimension(230, 45));
        btn_trangchu.setMinimumSize(new java.awt.Dimension(230, 45));
        btn_trangchu.setPreferredSize(new java.awt.Dimension(230, 45));
        btn_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trangchuActionPerformed(evt);
            }
        });

        btn_datphong.setText("ĐẶT PHÒNG");
        btn_datphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datphongActionPerformed(evt);
            }
        });

        btn_quanlyphong.setText("QUẢN LÝ PHÒNG");
        btn_quanlyphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlyphongActionPerformed(evt);
            }
        });

        btn_quanlydatphong.setText("QUẢN LÝ ĐẶT PHÒNG");
        btn_quanlydatphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlydatphongActionPerformed(evt);
            }
        });

        btn_quanlykhachhang.setText("QUẢN LÝ KHÁCH HÀNG");
        btn_quanlykhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlykhachhangActionPerformed(evt);
            }
        });

        btn_quanlydichvu.setText("QUẢN LÝ DỊCH VỤ");
        btn_quanlydichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanlydichvuActionPerformed(evt);
            }
        });

        btn_taikhoan.setText("TÀI KHOẢN");
        btn_taikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taikhoanActionPerformed(evt);
            }
        });

        btn_dangxuat.setText("ĐĂNG XUẤT");
        btn_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangxuatActionPerformed(evt);
            }
        });

        btn_thoat.setText("THOÁT HỆ THỐNG");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_westLayout = new javax.swing.GroupLayout(jpn_west);
        jpn_west.setLayout(jpn_westLayout);
        jpn_westLayout.setHorizontalGroup(
            jpn_westLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_westLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpn_westLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_quanlydatphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_quanlyphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_datphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_quanlykhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_quanlydichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_taikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpn_westLayout.setVerticalGroup(
            jpn_westLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_westLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btn_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_datphong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_quanlyphong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_quanlydatphong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_quanlykhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_quanlydichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jpn_west, java.awt.BorderLayout.LINE_START);

        jpn_center.setLayout(new java.awt.CardLayout());
        getContentPane().add(jpn_center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trangchuActionPerformed
        show_Panel("TRANGCHU");
        
    }//GEN-LAST:event_btn_trangchuActionPerformed

    private void btn_quanlyphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlyphongActionPerformed
        show_Panel("QUANLYPHONG");
    }//GEN-LAST:event_btn_quanlyphongActionPerformed

    private void btn_quanlykhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlykhachhangActionPerformed
        show_Panel("QUANLYKHACHHANG");
    }//GEN-LAST:event_btn_quanlykhachhangActionPerformed

    private void btn_quanlydichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlydichvuActionPerformed
        show_Panel("QUANLYDICHVU");
    }//GEN-LAST:event_btn_quanlydichvuActionPerformed

    private void btn_taikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taikhoanActionPerformed
        show_Panel("TAIKHOAN");
    }//GEN-LAST:event_btn_taikhoanActionPerformed

    private void btn_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangxuatActionPerformed
         int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        if (confirm == JOptionPane.YES_OPTION) {
            new Form_DangNhap().setVisible(true);
            this.dispose();
        }else{
            
        }
    }//GEN-LAST:event_btn_dangxuatActionPerformed

    private void btn_datphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datphongActionPerformed
        show_Panel("DATPHONG");
    }//GEN-LAST:event_btn_datphongActionPerformed

    private void btn_quanlydatphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanlydatphongActionPerformed
        show_Panel("QUANLYDATPHONG");
    }//GEN-LAST:event_btn_quanlydatphongActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc muốn thoát hệ thống không ?",
                "Kết thúc",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(choice==JOptionPane.YES_OPTION){
            System.exit(0);
        }else{
            
        }
    }//GEN-LAST:event_btn_thoatActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_zMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JButton btn_datphong;
    private javax.swing.JButton btn_quanlydatphong;
    private javax.swing.JButton btn_quanlydichvu;
    private javax.swing.JButton btn_quanlykhachhang;
    private javax.swing.JButton btn_quanlyphong;
    private javax.swing.JButton btn_taikhoan;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_trangchu;
    private javax.swing.JPanel jpn_center;
    private javax.swing.JPanel jpn_header;
    private javax.swing.JPanel jpn_west;
    private javax.swing.JLabel lbl_tieude;
    // End of variables declaration//GEN-END:variables
}
