/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.controller_TaiKhoan;
import javax.swing.JOptionPane;
import zhelp.MaHoa;
/**
 *
 * @author luuxu
 */
public class Form_Dangky extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_Dangky.class.getName());

    /**
     * Creates new form Form_Dangky
     */
    controller_TaiKhoan service = new controller_TaiKhoan();
    public Form_Dangky() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        lbl_an.setVisible(false);      
        txt_matkhau.setEchoChar('*');  // mật khẩu đang bị ẩn
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_taikhoan = new javax.swing.JTextField();
        txt_matkhau = new javax.swing.JPasswordField();
        txt_nhaplaimatkhau = new javax.swing.JPasswordField();
        lbl_hien = new javax.swing.JLabel();
        lbl_an = new javax.swing.JLabel();
        txt_tieptuc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng ký");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tài khoản :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mật khẩu :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nhập lại mật khẩu :");

        txt_taikhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txt_matkhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_nhaplaimatkhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lbl_hien.setText("Hiện");
        lbl_hien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_hienMouseClicked(evt);
            }
        });

        lbl_an.setText("Ẩn");
        lbl_an.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_anMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_taikhoan)
                            .addComponent(txt_nhaplaimatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(txt_matkhau)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_hien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_an)))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_taikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_matkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hien)
                    .addComponent(lbl_an))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nhaplaimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txt_tieptuc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_tieptuc.setText("Tiếp tục");
        txt_tieptuc.setPreferredSize(new java.awt.Dimension(130, 45));
        txt_tieptuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tieptucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_tieptuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tieptuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean isValidUsername(String tk) {
        // 5-50 ký tự, chỉ chữ hoa, chữ thường và số
        String regex = "^[a-zA-Z0-9]{5,50}$";
        return tk.matches(regex);
    }
    public boolean isValidPassword(String mk) {
        // 5-100 ký tự, ít nhất 1 chữ hoa, 1 chữ thường, 1 ký tự đặc biệt
        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9]).{5,100}$";
        return mk.matches(regex);
    }


    private void txt_tieptucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tieptucActionPerformed
        String tk = txt_taikhoan.getText().trim();
        String mk = new String(txt_matkhau.getPassword());
        String remk = new String(txt_nhaplaimatkhau.getPassword());
        String hashmk = MaHoa.encrypt_md5(mk);
        if (tk.isEmpty() || mk.isEmpty() || remk.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }

        if (!mk.equals(remk)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không khớp!");
            return;
        }
        
        if(tk.equals(mk)){
            JOptionPane.showMessageDialog(this, "Tài khoản và mật khẩu không được trùng nhau!");
            return;
        }
        
        if (service.is_Exist(tk)) {
            JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại!"+
                    "\nVui lòng chọn Tài khoản khác");
            return;
        }
        if (!isValidUsername(tk)) {
            JOptionPane.showMessageDialog(this, "Tài khoản không hợp lệ! "
                    + "(5-50 ký tự, chỉ chữ và số)"); 
            return;
        }

        if (!isValidPassword(mk)) {
            JOptionPane.showMessageDialog(this,  "Mật khẩu không hợp lệ! "
                    + "(5-100 ký tự, có chữ hoa, chữ thường, ký tự đặc biệt)");
            return;
        }

        boolean kq = service.register_KH(tk, hashmk);
        
        if(kq){
            JOptionPane.showMessageDialog(this, 
                    "Đăng ký khách hàng thành công!"+"\nHãy đăng nhập!");
            new Form_DangNhap().setVisible(true);
            this.dispose();
        }else {
        JOptionPane.showMessageDialog(this, "Đăng ký thất bại! ");
        }
    }//GEN-LAST:event_txt_tieptucActionPerformed

    private void lbl_hienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hienMouseClicked
        txt_matkhau.setEchoChar((char) 0);
        lbl_an.setVisible(true);
        lbl_hien.setVisible(false);
    }//GEN-LAST:event_lbl_hienMouseClicked

    private void lbl_anMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_anMouseClicked
        txt_matkhau.setEchoChar('*');
        lbl_an.setVisible(false);
        lbl_hien.setVisible(true);
    }//GEN-LAST:event_lbl_anMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_Dangky().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_an;
    private javax.swing.JLabel lbl_hien;
    private javax.swing.JPasswordField txt_matkhau;
    private javax.swing.JPasswordField txt_nhaplaimatkhau;
    private javax.swing.JTextField txt_taikhoan;
    private javax.swing.JButton txt_tieptuc;
    // End of variables declaration//GEN-END:variables
}
