/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.controller_DatPhong;
import controller.controller_DichVu;
import controller.controller_KhachHang;
import java.awt.Component;
import java.awt.Container;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import model.DichVu;
import model.KhachHang;
import model.Phong;
import model.Session;

/**
 *
 * @author luuxu
 */
public class Form_Datphong extends javax.swing.JPanel {
    private final DefaultTableModel tableModel = new DefaultTableModel();
    private controller_DatPhong ctrDP=new controller_DatPhong();
    private controller_DichVu ctrDv=new controller_DichVu();
    private controller_KhachHang ctrKh=new controller_KhachHang();
    private List<DichVu> dichVu=new ArrayList<>();
    private List<Phong> listPhong=new ArrayList<>();
    private Phong phong=new Phong();
    private KhachHang khachHang=null;
    private int tienDV=0;
    private DefaultListModel<String> modelListDV=new DefaultListModel<>();
    private DefaultListModel<String> modelLuaChon=new DefaultListModel<>();
    
    public Form_Datphong() {
        initComponents();
        panelDatPhong.setVisible(false);
        String []colsName = {"Mã phòng", "Tên phòng", "Loại phòng", "Sức chứa", "Tiện nghi","Giá phòng"};
        tableModel.setColumnIdentifiers(colsName);
        tblDatPhong.setModel(tableModel);
        listDichVu.setModel(modelListDV);
        listLuaChon.setModel(modelLuaChon);
        dichVu=ctrDv.getAllDichVu();
    }
    public void ClearData() {
    //Lay chi so dong cuoi cung
        int n=tableModel.getRowCount()-1;
        for(int i=n;i>=0;i--)
        tableModel.removeRow(i);//Remove tung dong
    }
    public void resetDangKiPhong(Container container){
        for(Component c:container.getComponents()){
            if(c instanceof JTextField){
                ((JTextField) c).setText("");
            }
            else if (c instanceof org.jdesktop.swingx.JXDatePicker) {
            ((org.jdesktop.swingx.JXDatePicker) c).setDate(null);
            }
            else if(c instanceof JList){
                if(c==listLuaChon){
                    modelLuaChon.clear();
                }
            }
            else if(c instanceof Container){
                resetDangKiPhong((Container)c);
            }
        }   
    }
    public void setTonTaiGmail(boolean x){
        tfHovaten.setEnabled(x);
        tfDiaChi.setEnabled(x);
        tfCccd.setEnabled(x);
        tfSdt.setEnabled(x);
    }
    public void setNULL(){
        tfHovaten.setText("");
        tfDiaChi.setText("");
        tfCccd.setText("");
        tfSdt.setText("");        
    }    
    public void setTongTienDichVu(int x){
        String luu = String.valueOf(x);
        StringBuilder kq = new StringBuilder();
        int count = 0;
         for (int i = luu.length() - 1; i >= 0; i--) {
            kq.insert(0, luu.charAt(i));
            count++;
            if (count % 3 == 0 && i != 0) {
                kq.insert(0, '.'); 
            }
        }     
        tfTongtiendichvu.setText(kq.toString());
    }
    public int tinhTienDichVu(String x){
        for(DichVu c:dichVu){
            if(c.getTenDichVu() == null ? x == null : c.getTenDichVu().equals(x)) return c.getGiaDichVu();
        }
        return 0;
    }
    public void setThongTinPhong(){
        tfMaPhong.setText(String.valueOf(phong.getMaPhong()));
        tfMaPhong.setEnabled(false);
        tfTenPhong.setText(phong.getTenPhong());
        tfTenPhong.setEnabled(false);
        dpkDKNgayDen.setDate(dpkNgayDen.getDate());
        dpkDKNgayDen.setEnabled(false);
        dpkDKNgayDi.setDate(dpkNgayDi.getDate());
        dpkDKNgayDi.setEnabled(false);
        tfGiaPhong.setText(String.valueOf(phong.getGiaPhong()));
        tfGiaPhong.setEnabled(false);
        long days=((dpkNgayDi.getDate().getTime()-dpkNgayDen.getDate().getTime())/(1000*60*60*24));
        tfSongay.setText(String.valueOf(days));
        tfSongay.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatPhong = new javax.swing.JPanel();
        btnDongFormDangKi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelDienTTDatPhong = new javax.swing.JPanel();
        panelThongTinCaNhan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfHovaten = new javax.swing.JTextField();
        tfDiaChi = new javax.swing.JTextField();
        tfCccd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfGmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfSdt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panelYeuCauDatPhong = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfMaPhong = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dpkDKNgayDen = new org.jdesktop.swingx.JXDatePicker();
        jLabel14 = new javax.swing.JLabel();
        tfGiaPhong = new javax.swing.JTextField();
        tfTenPhong = new javax.swing.JTextField();
        tfSongay = new javax.swing.JTextField();
        dpkDKNgayDi = new org.jdesktop.swingx.JXDatePicker();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelDichVu = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDichVu = new javax.swing.JList<>();
        btnChondv = new javax.swing.JButton();
        btnXoadv = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listLuaChon = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        tfTongtiendichvu = new javax.swing.JTextField();
        btnDatPhongin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        panelTimKiemPhong = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dpkNgayDen = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();
        dpkNgayDi = new org.jdesktop.swingx.JXDatePicker();
        btnDatPhong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatPhong = new javax.swing.JTable();
        btLamMoi = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDatPhong.setBackground(new java.awt.Color(204, 255, 204));

        btnDongFormDangKi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDongFormDangKi.setForeground(new java.awt.Color(204, 0, 0));
        btnDongFormDangKi.setText("X");
        btnDongFormDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongFormDangKiActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBar(null);

        panelThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1000, 522));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("-- Thông tin cá nhân --");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Họ và tên:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Số CCCD:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Địa chỉ:");

        tfHovaten.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        tfDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        tfCccd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Gmai:");

        tfGmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGmailActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Số điện thoại:");

        tfSdt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel21.setForeground(new java.awt.Color(255, 102, 102));
        jLabel21.setText("*Thay đổi thông tin cá nhân trong mục \"Tài khoản\"");

        javax.swing.GroupLayout panelThongTinCaNhanLayout = new javax.swing.GroupLayout(panelThongTinCaNhan);
        panelThongTinCaNhan.setLayout(panelThongTinCaNhanLayout);
        panelThongTinCaNhanLayout.setHorizontalGroup(
            panelThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinCaNhanLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongTinCaNhanLayout.createSequentialGroup()
                        .addGroup(panelThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongTinCaNhanLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfHovaten, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                        .addComponent(tfCccd))
                                    .addGap(78, 78, 78)))
                            .addGroup(panelThongTinCaNhanLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(361, 361, 361)))
                        .addGap(14, 14, 14)
                        .addGroup(panelThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(panelThongTinCaNhanLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)))
                .addGap(50, 50, 50))
        );
        panelThongTinCaNhanLayout.setVerticalGroup(
            panelThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinCaNhanLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addGroup(panelThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfHovaten, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCccd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(tfSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("-- Yêu cầu đặt phòng --");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Mã phòng:");

        tfMaPhong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Ngày đến:");

        dpkDKNgayDen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Giá phòng:");

        tfGiaPhong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        tfTenPhong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfTenPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenPhongActionPerformed(evt);
            }
        });

        tfSongay.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        dpkDKNgayDi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        dpkDKNgayDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpkDKNgayDiActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setText("Tên phòng:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setText("Ngày đi:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setText("Số ngày ở lại:");

        javax.swing.GroupLayout panelYeuCauDatPhongLayout = new javax.swing.GroupLayout(panelYeuCauDatPhong);
        panelYeuCauDatPhong.setLayout(panelYeuCauDatPhongLayout);
        panelYeuCauDatPhongLayout.setHorizontalGroup(
            panelYeuCauDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYeuCauDatPhongLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelYeuCauDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(panelYeuCauDatPhongLayout.createSequentialGroup()
                        .addGroup(panelYeuCauDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelYeuCauDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dpkDKNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(77, 77, 77)
                .addGroup(panelYeuCauDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelYeuCauDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTenPhong)
                    .addComponent(dpkDKNgayDi, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(tfSongay))
                .addGap(590, 590, 590))
        );
        panelYeuCauDatPhongLayout.setVerticalGroup(
            panelYeuCauDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYeuCauDatPhongLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addGap(29, 29, 29)
                .addGroup(panelYeuCauDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(24, 24, 24)
                .addGroup(panelYeuCauDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dpkDKNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpkDKNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(panelYeuCauDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSongay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("-- Đăng kí dịch vụ --");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)), "Dịch vụ của khách sạn", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        listDichVu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jScrollPane2.setViewportView(listDichVu);

        btnChondv.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnChondv.setText("Chọn");
        btnChondv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChondvActionPerformed(evt);
            }
        });

        btnXoadv.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXoadv.setText("Xoá");
        btnXoadv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoadvActionPerformed(evt);
            }
        });

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)), "Lựa chọn của bạn", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        listLuaChon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jScrollPane4.setViewportView(listLuaChon);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Tổng số tiền dịch vụ");

        tfTongtiendichvu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnDatPhongin.setText("Đặt phòng");
        btnDatPhongin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhonginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDichVuLayout = new javax.swing.GroupLayout(panelDichVu);
        panelDichVu.setLayout(panelDichVuLayout);
        panelDichVuLayout.setHorizontalGroup(
            panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDichVuLayout.createSequentialGroup()
                .addGroup(panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDichVuLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(panelDichVuLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnXoadv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnChondv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(tfTongtiendichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelDichVuLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnDatPhongin)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        panelDichVuLayout.setVerticalGroup(
            panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDichVuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addGroup(panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDichVuLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnChondv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoadv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDichVuLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .addGroup(panelDichVuLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel16)
                        .addGap(8, 8, 8)
                        .addComponent(tfTongtiendichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(btnDatPhongin)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout panelDienTTDatPhongLayout = new javax.swing.GroupLayout(panelDienTTDatPhong);
        panelDienTTDatPhong.setLayout(panelDienTTDatPhongLayout);
        panelDienTTDatPhongLayout.setHorizontalGroup(
            panelDienTTDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDienTTDatPhongLayout.createSequentialGroup()
                .addGroup(panelDienTTDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelYeuCauDatPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelThongTinCaNhan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(panelDienTTDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDienTTDatPhongLayout.createSequentialGroup()
                    .addComponent(panelDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 375, Short.MAX_VALUE)))
        );
        panelDienTTDatPhongLayout.setVerticalGroup(
            panelDienTTDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDienTTDatPhongLayout.createSequentialGroup()
                .addComponent(panelThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelYeuCauDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
            .addGroup(panelDienTTDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDienTTDatPhongLayout.createSequentialGroup()
                    .addContainerGap(502, Short.MAX_VALUE)
                    .addComponent(panelDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jScrollPane3.setViewportView(panelDienTTDatPhong);

        javax.swing.GroupLayout panelDatPhongLayout = new javax.swing.GroupLayout(panelDatPhong);
        panelDatPhong.setLayout(panelDatPhongLayout);
        panelDatPhongLayout.setHorizontalGroup(
            panelDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatPhongLayout.createSequentialGroup()
                .addContainerGap(961, Short.MAX_VALUE)
                .addComponent(btnDongFormDangKi)
                .addContainerGap())
            .addGroup(panelDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatPhongLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3)
                    .addContainerGap()))
        );
        panelDatPhongLayout.setVerticalGroup(
            panelDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatPhongLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnDongFormDangKi))
            .addGroup(panelDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatPhongLayout.createSequentialGroup()
                    .addContainerGap(34, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        add(panelDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 990, 540));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(610, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Đặt phòng");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Khám phá thế giới của riêng bạn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 736, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Ngày nhận phòng");

        dpkNgayDen.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                dpkNgayDenAncestorRemoved(evt);
            }
        });
        dpkNgayDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpkNgayDenActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Ngày rời đi");

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChiTiet.setText("Chi tiết");

        dpkNgayDi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                dpkNgayDiAncestorRemoved(evt);
            }
        });
        dpkNgayDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpkNgayDiActionPerformed(evt);
            }
        });

        btnDatPhong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDatPhong.setText("Đặt phòng");
        btnDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongActionPerformed(evt);
            }
        });

        tblDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phòng", "Tên phòng", "Loại phòng", "Sức chứa", "Tiện nghi", "Giá phòng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatPhong.setRowHeight(33);
        tblDatPhong.setShowHorizontalLines(true);
        tblDatPhong.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblDatPhong);
        if (tblDatPhong.getColumnModel().getColumnCount() > 0) {
            tblDatPhong.getColumnModel().getColumn(0).setMinWidth(70);
            tblDatPhong.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblDatPhong.getColumnModel().getColumn(0).setMaxWidth(70);
            tblDatPhong.getColumnModel().getColumn(1).setMinWidth(200);
            tblDatPhong.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblDatPhong.getColumnModel().getColumn(1).setMaxWidth(200);
            tblDatPhong.getColumnModel().getColumn(2).setMinWidth(90);
            tblDatPhong.getColumnModel().getColumn(2).setPreferredWidth(90);
            tblDatPhong.getColumnModel().getColumn(2).setMaxWidth(90);
            tblDatPhong.getColumnModel().getColumn(3).setMinWidth(90);
            tblDatPhong.getColumnModel().getColumn(3).setPreferredWidth(90);
            tblDatPhong.getColumnModel().getColumn(3).setMaxWidth(90);
            tblDatPhong.getColumnModel().getColumn(4).setMinWidth(370);
            tblDatPhong.getColumnModel().getColumn(4).setPreferredWidth(370);
            tblDatPhong.getColumnModel().getColumn(4).setMaxWidth(370);
        }

        btLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLamMoi.setText("Làm mới");
        btLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTimKiemPhongLayout = new javax.swing.GroupLayout(panelTimKiemPhong);
        panelTimKiemPhong.setLayout(panelTimKiemPhongLayout);
        panelTimKiemPhongLayout.setHorizontalGroup(
            panelTimKiemPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTimKiemPhongLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(99, 99, 99)
                .addComponent(jLabel4))
            .addGroup(panelTimKiemPhongLayout.createSequentialGroup()
                .addComponent(dpkNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(dpkNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnDatPhong))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelTimKiemPhongLayout.setVerticalGroup(
            panelTimKiemPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTimKiemPhongLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelTimKiemPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(panelTimKiemPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dpkNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpkNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelContent.add(panelTimKiemPhong);

        add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, 1090, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void dpkNgayDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpkNgayDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpkNgayDenActionPerformed

    private void dpkNgayDenAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dpkNgayDenAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_dpkNgayDenAncestorRemoved

    private void dpkNgayDiAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dpkNgayDiAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_dpkNgayDiAncestorRemoved

    private void dpkNgayDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpkNgayDiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpkNgayDiActionPerformed

    private void btnDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongActionPerformed
        
        //  Đặt panelDatPhong lên trên cùng (Z-order = 0)
        // 'this' là Form_Datphong, container cha chứa cả panelContent và panelDatPhong
        int row = tblDatPhong.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn phòng!");
            return;
        }
        resetDangKiPhong(panelDatPhong);
        phong.setMaPhong((int) tblDatPhong.getValueAt(row, 0));
        phong.setTenPhong(tblDatPhong.getValueAt(row, 1).toString());
        phong.setGiaPhong((int) tblDatPhong.getValueAt(row, 5));
        setThongTinPhong();
        this.setComponentZOrder(panelDatPhong, 0); 
        panelContent.setVisible(false);
        panelDatPhong.setVisible(true); 
        List<String> listTenDichVu=ctrDv.getAllTenDichVu();
        for(String c:listTenDichVu){
            modelListDV.addElement(c);
        }
        setTonTaiGmail(false);
        setNULL();
        //Yêu cầu container cha vẽ lại để cập nhật thứ tự lớp
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnDatPhongActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        try{
            Date ngayDen=dpkNgayDen.getDate();
            Date ngayDi=dpkNgayDi.getDate();
            if( ngayDen==null || ngayDi==null || ngayDi.compareTo(ngayDen) <= 0){
                JOptionPane.showMessageDialog(null,"Kiem tra lai noi dung da nhap! ", "Thong bao",1);
                return;
            }
            listPhong=ctrDP.getPhongTrong(new java.sql.Date(ngayDen.getTime()),new java.sql.Date(ngayDi.getTime()));
            if(listPhong.isEmpty()){
                JOptionPane.showMessageDialog(null,"Khong co phong trong! ", "Thong bao",1);
                return;
            } 
            ClearData();
            for(Phong x: listPhong){
                //String[] rows={String.valueOf(x.getMaPhong()),x.getTenPhong(),"Phòng đôi", "2 người", "Tivi,Wifi,Bồn tắm, Ban công,View biển",String.valueOf(x.getGiaPhong())};
                Object[] rows = {
                            x.getMaPhong(),        
                            x.getTenPhong(),       
                            "Phòng đôi",           
                            "2 người",             
                            "Tivi,Wifi,Bồn tắm, Ban công,View biển",
                            x.getGiaPhong()        
                };
                tableModel.addRow(rows);
            }
                        jScrollPane1.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Khong co phong trong! ", "Thong bao",1);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLamMoiActionPerformed
        // TODO add your handling code here:
        ClearData();
        dpkNgayDen.setDate(null);
        dpkNgayDi.setDate(null);
    }//GEN-LAST:event_btLamMoiActionPerformed

    private void btnDongFormDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongFormDangKiActionPerformed
        // TODO add your handling code here:
        // 1. Ẩn panel Dat Phong (nằm trên)
        panelDatPhong.setVisible(false);
    
        // . Hiện panel cũ (nằm dưới)
        panelContent.setVisible(true); 

        // Cập nhật giao diện
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnDongFormDangKiActionPerformed

    private void tfGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGmailActionPerformed
        // TODO add your handling code here:
        String email=tfGmail.getText().trim();
        //System.out.println(Session.getGmail());
        if(!email.equals(Session.getGmail())){
            JOptionPane.showMessageDialog(this, "Hãy nhập đúng Gmail đã đăng ký cùng tài khoàn nay!");
            return;
        }
        khachHang=ctrKh.getKhachHangByEmail(email);
        if(khachHang==null) {setTonTaiGmail(true);setNULL();}
        else{
            tfHovaten.setText(khachHang.getTenKH());
            tfDiaChi.setText(khachHang.getDiaChi());
            tfCccd.setText(khachHang.getCccd());
            tfGmail.setText(khachHang.getEmail());
            tfSdt.setText(khachHang.getSoDT());
            setTonTaiGmail(false);
        }     
    }//GEN-LAST:event_tfGmailActionPerformed

    private void btnChondvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChondvActionPerformed
        // TODO add your handling code here:
        List<String> selectedValues=listDichVu.getSelectedValuesList();
        for(String v: selectedValues){
            if(!modelLuaChon.contains(v))
            {
                tienDV+=tinhTienDichVu(v);
                modelLuaChon.addElement(v);
            }    
        }
        setTongTienDichVu(tienDV);
    }//GEN-LAST:event_btnChondvActionPerformed

    private void btnXoadvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoadvActionPerformed
        // TODO add your handling code here:
        List<String> selectedValues=listLuaChon.getSelectedValuesList();
        for(String v: selectedValues){
                tienDV-=tinhTienDichVu(v);
        }
        
        // Xoá từ cuối lên đầu để tránh lệch index
        int[] selectedIndices = listLuaChon.getSelectedIndices();
        for (int i = selectedIndices.length - 1; i >= 0; i--) {
            modelLuaChon.remove(selectedIndices[i]);
        }
        setTongTienDichVu(tienDV);
    }//GEN-LAST:event_btnXoadvActionPerformed

    private void tfTenPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenPhongActionPerformed

    private void dpkDKNgayDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpkDKNgayDiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpkDKNgayDiActionPerformed

    private void btnDatPhonginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhonginActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(
        null,
        "Bạn đã chắc chắn với thông tin cung cấp?",
        "Xác nhận",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
        ); 
        if(result== JOptionPane.YES_OPTION) 
        {
            // 1. Ẩn panel Dat Phong (nằm trên)
            panelDatPhong.setVisible(false);
            // . Hiện panel cũ (nằm dưới)
            panelContent.setVisible(true); 

            // Cập nhật giao diện
            this.revalidate();
            this.repaint();
            return;
            //xuLiDatPhong();
        }
    }//GEN-LAST:event_btnDatPhonginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLamMoi;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnChondv;
    private javax.swing.JButton btnDatPhong;
    private javax.swing.JButton btnDatPhongin;
    private javax.swing.JButton btnDongFormDangKi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoadv;
    private org.jdesktop.swingx.JXDatePicker dpkDKNgayDen;
    private org.jdesktop.swingx.JXDatePicker dpkDKNgayDi;
    private org.jdesktop.swingx.JXDatePicker dpkNgayDen;
    private org.jdesktop.swingx.JXDatePicker dpkNgayDi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listDichVu;
    private javax.swing.JList<String> listLuaChon;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelDatPhong;
    private javax.swing.JPanel panelDichVu;
    private javax.swing.JPanel panelDienTTDatPhong;
    private javax.swing.JPanel panelThongTinCaNhan;
    private javax.swing.JPanel panelTimKiemPhong;
    private javax.swing.JPanel panelYeuCauDatPhong;
    private javax.swing.JTable tblDatPhong;
    private javax.swing.JTextField tfCccd;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfGiaPhong;
    private javax.swing.JTextField tfGmail;
    private javax.swing.JTextField tfHovaten;
    private javax.swing.JTextField tfMaPhong;
    private javax.swing.JTextField tfSdt;
    private javax.swing.JTextField tfSongay;
    private javax.swing.JTextField tfTenPhong;
    private javax.swing.JTextField tfTongtiendichvu;
    // End of variables declaration//GEN-END:variables
}
