/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.TaiKhoan;
import controller.controller_TaiKhoan;
import java.awt.Color;
import model.Session;
import zhelp.MaHoa;
/**
 *
 * @author luuxu
 */
public class Form_DangNhap extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_DangNhap.class.getName());

    /**
     * Creates new form Form_DangNhap
     */
    controller_TaiKhoan ctrl_tk = new controller_TaiKhoan();
    public Form_DangNhap() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        lbl_an.setVisible(false);      
        txt_matkhau.setEchoChar('*');  // mật khẩu đang bị ẩn
        
        getContentPane().setBackground(new Color(235, 241, 255));  // xanh nhạt 

        // Panel chính
        lbl_an.setBackground(new Color(255, 255, 255));
        

        // Tiêu đề
        jLabel1.setForeground(new Color(0, 80, 160)); // xanh đậm 

        // Các label
        jLabel2.setForeground(new Color(40, 40, 40));
        jLabel3.setForeground(new Color(40, 40, 40));
        lbl_hien.setForeground(new Color(0, 102, 204));
        

        // TextField màu nhẹ 
        txt_taikhoan.setBackground(new Color(250, 250, 255));
        txt_matkhau.setBackground(new Color(250, 250, 255));

        txt_taikhoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 200, 230)));
        txt_matkhau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 200, 230)));

        // Nút đăng nhập - màu xanh 
        btn_dangnhap.setBackground(new Color(0, 120, 215));
        btn_dangnhap.setForeground(Color.WHITE);
       
        // Hover cho nút đăng nhập
        btn_dangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dangnhap.setBackground(new Color(0, 70, 160));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dangnhap.setBackground(new Color(0, 120, 215));
            }
        });

        // Nút đăng ký - xanh nhạt 
        btn_dangky.setBackground(new Color(0, 160, 240));
        btn_dangky.setForeground(Color.WHITE);
        

        // Hover nút đăng ký
        btn_dangky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dangky.setBackground(new Color(0, 100, 180));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dangky.setBackground(new Color(0, 160, 240));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_taikhoan = new javax.swing.JTextField();
        txt_matkhau = new javax.swing.JPasswordField();
        lbl_an = new javax.swing.JLabel();
        lbl_hien = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_dangky = new javax.swing.JButton();
        btn_dangnhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng nhập");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tài khoản :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mật khẩu :");

        txt_taikhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_taikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_taikhoanActionPerformed(evt);
            }
        });

        txt_matkhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lbl_an.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_an.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_an.setText("Ẩn");
        lbl_an.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_anMouseClicked(evt);
            }
        });

        lbl_hien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_hien.setText("HIện ");
        lbl_hien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_hienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_hien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_an, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_matkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(txt_taikhoan))))
                .addContainerGap())
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_taikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_matkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_hien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_an, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_dangky.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_dangky.setText("Đăng ký");
        btn_dangky.setPreferredSize(new java.awt.Dimension(130, 45));
        btn_dangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangkyActionPerformed(evt);
            }
        });
        jPanel2.add(btn_dangky);

        btn_dangnhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_dangnhap.setText("Đăng nhập");
        btn_dangnhap.setPreferredSize(new java.awt.Dimension(130, 45));
        btn_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapActionPerformed(evt);
            }
        });
        jPanel2.add(btn_dangnhap);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapActionPerformed
        String tk = txt_taikhoan.getText().trim();
        String mk = new String(txt_matkhau.getPassword());
        String hashmk = MaHoa.encrypt_md5(mk);
        if (tk.trim().isEmpty() || mk.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ tài khoản và mật khẩu!");
            return;
        }

        // Tài khoản không hợp lệ
        if (!tk.matches("[a-zA-Z0-9_]+")) {
            JOptionPane.showMessageDialog(this, "Tài khoản không được chứa ký tự đặc biệt!");
            txt_taikhoan.setText("");
            txt_matkhau.setText("");
            txt_taikhoan.requestFocus();
            return;
        }
        TaiKhoan taikhoan = ctrl_tk.login_NV(tk, hashmk);

        if (taikhoan != null) {
            int quyen = taikhoan.getQuyen();
            String vaitro = (quyen == 0) ? "Nhân viên" : "Khách hàng";
            JOptionPane.showMessageDialog(this, 
                    "Đăng nhập thành công !"+"\nVai trò : "+vaitro);  
            new Form_zMain().setVisible(true);
            Session.setGmail(tk);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Tài khoản không đúng !");
            txt_taikhoan.setText("");
            txt_matkhau.setText("");
            txt_taikhoan.requestFocus();
        }
    }//GEN-LAST:event_btn_dangnhapActionPerformed

    private void btn_dangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangkyActionPerformed
        new Form_Dangky().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_dangkyActionPerformed

    private void lbl_hienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hienMouseClicked
        txt_matkhau.setEchoChar((char) 0);  // hiện mật khẩu

        lbl_hien.setVisible(false);        // ẩn 
        lbl_an.setVisible(true);           // hiện 
    }//GEN-LAST:event_lbl_hienMouseClicked

    private void lbl_anMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_anMouseClicked
        txt_matkhau.setEchoChar('*');      // ẩn mật khẩu

        lbl_an.setVisible(false);          // ẩn 
        lbl_hien.setVisible(true);         // hiện 
    }//GEN-LAST:event_lbl_anMouseClicked

    private void txt_taikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_taikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_taikhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_DangNhap().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JButton btn_dangky;
    private javax.swing.JButton btn_dangnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_an;
    private javax.swing.JLabel lbl_hien;
    private javax.swing.JPasswordField txt_matkhau;
    private javax.swing.JTextField txt_taikhoan;
    // End of variables declaration//GEN-END:variables
}
